### PR TITLE
Remove a broken link

### PR DESCRIPTION
**Pull request by miketheman**

### CODE REVIEW

**Comment by juliandunn** [comment]
We have this problem too.
:shipit: :grin:

**Comment by miketheman** [comment]
@technicalpickles you know you want to push that green button, right? :)

**Comment by technicalpickles** [comment]
Somehow wasn't watching the repo, sorry.

**Comment by technicalpickles** [comment]
@miketheman I added you as a collaborator if you don't mind :grin: if you send me your rubygems email, I can add you to be able to release too.

**Comment by miketheman** [comment]
Thanks! My rubygems email is the same one associated with my GH account. https://github.com/miketheman

**Comment by miketheman** [comment]
@technicalpickles I tried to do the release today, but got an `You do not have permission to push to this gem.`

**Comment by technicalpickles** [comment]
@miketheman I was traveling this week, and didn't get a chance to add you. Should be good now!

**Comment by miketheman** [comment]
Confirmed, and released!

**Pull request merged**
