### PR TITLE
Clean up dead squirrels

### PR DESCRIPTION
**Pull request by nilbus**
Removed images that no longer work:
- http://images.cheezburger.com/completestore/2011/11/2/aa83c0c4-2123-4bd3-8097-966c9461b30c.jpg
- http://images.cheezburger.com/completestore/2011/11/2/46e81db3-bead-4e2e-a157-8edd0339192f.jpg
- http://gifs.gifbin.com/092010/1285616410_ship-launch-floods-street.gif
- http://img70.imageshack.us/img70/4853/cutesquirrels27rn9.jpg
- http://img70.imageshack.us/img70/9615/cutesquirrels15ac7.jpg

### CODE REVIEW

**Comment by miketheman** [comment]
😢 Thanks.
We need more squirrels!!

**Comment by nilbus** [comment]
I'm actually grabbing some right now :) Posting soon.

**Comment by nilbus** [comment]
… and here are a few more. Would you like to add these as well? These are re-hosted on imgur, so hopefully they'll be more durable.

- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by nilbus** [comment]
Fixed all the image links :smile:

**Comment by nilbus** [comment]
Opened #3 with new squirrels

**Comment by miketheman** [comment]
Closing, superseded by #3

**Pull request closed without merging**
